# Generated by Django 3.2.21 on 2023-09-10 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TicketTitle', models.CharField(max_length=250)),
                ('TicketProblem', models.TextField()),
                ('TicketCreationDate', models.DateTimeField(auto_now_add=True)),
                ('TicketUpdatedDate', models.DateTimeField(auto_now=True)),
                ('TicketStatus', models.CharField(default='Minor', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
