# Generated by Django 4.2.4 on 2023-08-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ticket_level',
            field=models.CharField(choices=[('MIN', 'Minor'), ('MAJ', 'Major'), ('CRIT', 'Critical')], default='MIN', max_length=20),
        ),
    ]
