# Generated by Django 3.2.21 on 2023-09-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HelpDeskProject', '0002_post_ticket_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
